networks=["jio","Tata Docomo","airtel","BSNL"]
vi=["vodafone","idea"]
networks.extend(vi)
networks.append("uninor")
networks.insert(1,"aircel")
networks.remove("BSNL")
networks.index("jio")
print(networks[:])
networks[2]="Airtel"
print(networks)
print(networks[1:])
mobiles=["MI","samsung","realme","apple","vivo"]
print(mobiles.reverse())
print(mobiles)
mobiles.clear()
print(mobiles)
alph=["b","a","a","b","c"]
print(alph.count("a"))
alph.sort()
print(alph)
num=["1","-8","906","0","5"]
num.sort()
print(num)
m=["4","8","5","87"]
m.reverse()
print(m)
b=m.copy()
print(b)
